services:
    backend:
        build: ./backend
        ports:
            - "8000:80"
        depends_on:
            - db
        volumes:
            - ./backend:/var/www/html
    frontend:
        build: ./frontend
        command: npm run serve
        volumes:
            - ./frontend:/app
        ports:
            - "8080:8080"
        environment:
            - NODE_ENV=development
    db:
        image: postgres:13
        environment:
            POSTGRES_DB: db
            POSTGRES_USER: root
            POSTGRES_PASSWORD: root
        ports:
            - "5432:5432"
        volumes:
            - db-data:/var/lib/postgresql/data
    pgadmin4:
        image: dpage/pgadmin4
        environment:
            PGADMIN_DEFAULT_EMAIL: admin@admin.com
            PGADMIN_DEFAULT_PASSWORD: root
        ports:
            - "8081:80"
        depends_on:
            - db
volumes:
    db-data:
